# Generated by Django 5.1.7 on 2025-04-07 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_stripeadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='query',
            name='references',
        ),
        migrations.RemoveField(
            model_name='query',
            name='response_text',
        ),
        migrations.AddField(
            model_name='query',
            name='documents',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='query',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
