# Generated by Django 5.1.7 on 2025-04-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentuser_student_id_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='student_id_text',
        ),
    ]
